#spring.data.mongodb.uri=mongodb+srv://sharmachirag73369_db_user:Chirag123@cluster0.aseumuq.mongodb.net/journaldb?retryWrites=true&w=majority
#spring.data.mongodb.database=journaldb
#spring.data.mongodb.auto-index-creation=true
#server.servlet.context-path=/journal